//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGPassManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilianVehiclePassView
    {
        public long NSGPassID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FullName { get; set; }
        public string RegistrationNumber { get; set; }
        public string VehicleType { get; set; }
        public string VehicleMake { get; set; }
        public string Designation { get; set; }
        public byte[] PassHolderPhoto { get; set; }
    }
}
