//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGPassManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilianPassDetail
    {
        public long CivilianPassDetailID { get; set; }
        public long NSGPassID { get; set; }
        public string Designation { get; set; }
        public string ContractorName { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CoreUser CoreUser { get; set; }
        public virtual NSGPass NSGPass { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
    }
}
