//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGPassManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestDependentPassDetailView
    {
        public long NSGPassID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FullName { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IdentificationMark { get; set; }
        public string RelativeOf { get; set; }
        public string NSGEmployeeCode { get; set; }
        public string RankName { get; set; }
        public string UnitName { get; set; }
        public byte[] PassHolderPhoto { get; set; }
    }
}
