//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGPassManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSGPass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NSGPass()
        {
            this.CivilianPassDetails = new HashSet<CivilianPassDetail>();
            this.GuestDependantPassDetails = new HashSet<GuestDependantPassDetail>();
            this.OutlivingPassDetails = new HashSet<OutlivingPassDetail>();
            this.VehiclePassDetails = new HashSet<VehiclePassDetail>();
            this.PassDocuments = new HashSet<PassDocument>();
        }
    
        public long NSGPassID { get; set; }
        public string MachineID { get; set; }
        public int PassTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string GuardianName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string PassHolderAddress { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public byte[] PassHolderPhoto { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CivilianPassDetail> CivilianPassDetails { get; set; }
        public virtual CoreCity CoreCity { get; set; }
        public virtual CorePassType CorePassType { get; set; }
        public virtual CoreState CoreState { get; set; }
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestDependantPassDetail> GuestDependantPassDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutlivingPassDetail> OutlivingPassDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclePassDetail> VehiclePassDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassDocument> PassDocuments { get; set; }
    }
}
